### ISSUE TITLE
Make --help print to stdout

### ISSUE THREAD

**Issue by rkulla** [monochromegane/the_platinum_searcher#153] opened 2016-09-18 19:26 UTC
Currently `pt --help` prints to stderr, but it should print to stdout for doing command-line operations  such as `pt --help | grep ignore`

Presumably this is because of https://github.com/monochromegane/the_platinum_searcher/blob/master/platinum_searcher.go#L55 And because there's no `Help` section in https://github.com/monochromegane/the_platinum_searcher/blob/master/option.go#L107

I don't have any more time to look into it any time soon. So if anyone wants to tackle this I think it would be better/more standard behavior, to output help to stdout (for piping to less, grep, etc).

**Comment by vbauerster** [comment] 2016-11-13 19:40
The issue is related not the `pt` codebase, but to the dependency on go-flags package, see [issue 194](https://github.com/jessevdk/go-flags/issues/194). It's fixed now, so you just need to rebuild the pt:
`go get -u github.com/monochromegane/the_platinum_searcher/...`

**Closed** 2016-11-13 20:23 UTC
